apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: user
    spec:
      containers:
        - command:
            - user
          image: ghcr.io/picop-rd/deathstarbench/hotelreservation:picop
          imagePullPolicy: Always
          name: hotel-reserv-user
          ports:
            - containerPort: 8086
          env:
            - name: JAEGER_SAMPLE_RATIO
              value: "0.1"
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '8087', '--admin-port', '9000', '--default-addr', 'localhost:8086', '--propagate=true', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'user']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 8087
            - name: admin
              containerPort: 9000
      restartPolicy: Always
status: {}
