name: Push HotelReservation
concurrency: ci-hotelReservation

on:
  push:
    branches: 
      - master
      - picop
      - base
    paths:
      - 'hotelReservation/**'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build tag
      id: tag
      run: |
        if [[ "${{ github.ref_name }}" == "master" ]]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi
    - uses: docker/build-push-action@v3
      with:
        context: ./hotelReservation
        push: true
        tags: ghcr.io/picop-rd/deathstarbench/hotelreservation:${{ steps.tag.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
